<?php
return [
    'gateway_url' => 'https://ecomm.prbb.ru:5445/cgi-bin/cgi_link',
    'return_url' => 'http://evolveskateboards.ru/payment/return_url',
    'mac_component1' => '802B7ACA7E4E9C1C20E79B14CCEE2EE2',
    'mac_component2' => '8719AA3FF2B343D669CA737E4BC32DDC',
    'terminal' => 'CIS0ET31',
    'merchant_id' => 'EPB3000E30001PB',
    'merchant_email' => 'ECOMM_TEST@PRBB.RU',
    'merchant_name' => 'Evolve',
    'merchant_url' => 'http://evolveskateboards.ru',
    'merchant_gmt' => '+3',
    'currency' => 'RUR',
    'country' => 'RU',
    'brands' => 'VISA,MASTERCARD',
    'use_post_for_request' => false,
    'debug_payment_gateway_response' => false,
    'testing' => true,
    'mac_fields' => ['NONCE', 'AMOUNT', 'ORDER', 'TIMESTAMP', 'TRTYPE', 'TERMINAL'],
];